{
 "title": "TestDashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "IoP Robots",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "target": "db.robots.aggregate\n([{\n\"$match\": {}}\n])",
     "type": "table"
    }
   ]
  },
  {
   "title": "IoP Capabilities",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "target": "db.capabilities.aggregate\n([{\n\"$match\": {}}\n])",
     "type": "table"
    }
   ]
  },
  {
   "title": "IoP Stations",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "target": "db.stations.aggregate\n([{\n\"$match\": {}}\n])",
     "type": "table"
    }
   ]
  },
  {
   "title": "IoP WorkPlans",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "target": "db.work_plans.aggregate\n([{\n\"$match\": {}}\n])",
     "type": "table"
    }
   ]
  }
 ]
}