{
 "title": "MainIoP",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "IoP Factories",
   "type": "dashlist",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 0 },
   "options": {
    "content": "<img src=https://www.wzl.rwth-aachen.de/global/show_picture.asp?id=aaaaaaaaabdtrye />\n           "
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Number of Factories",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "db.b24/factories.aggregate([\n{\"$match\": {}},\n{ \"$group\": { \"_id\": \"$physical_resource.abstract_resource.name\" } },\n{\"$count\": \"number_of_stations\"}\n])",
     "type": "table"
    }
   ]
  },
  {
   "title": "Number of Resources",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 4, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "db.b24/resources.aggregate([\n{\"$match\": {}},\n{ \"$group\": { \"_id\": \"$physical_resource.abstract_resource.name\" } },\n{\"$count\": \"number_of_resources\"}\n])",
     "type": "table"
    }
   ]
  },
  {
   "title": "Number of Stations",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 8, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "db.b24/stations.aggregate([\n{\"$match\": {}},\n{ \"$group\": { \"_id\": \"$physical_resource.abstract_resource.name\" } },\n{\"$count\": \"number_of_stations\"}\n])",
     "type": "table"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "target": "db.b24/factories.aggregate([\n{\n  \"$collStats\":\n    {\n      \"latencyStats\": { \"histograms\": true },\n      \"storageStats\": { \"scale\": 1024 },\n      \"count\": {},\n      \"queryExecStats\": {}\n    }\n}\n])",
     "type": "table"
    },
    {
     "target": "db.b24/resources.aggregate([\n{\n  \"$collStats\":\n    {\n      \"latencyStats\": { \"histograms\": true },\n      \"storageStats\": { \"scale\": 1024 },\n      \"count\": {},\n      \"queryExecStats\": {}\n    }\n}\n])",
     "type": "table"
    }
   ]
  }
 ]
}