{
 "title": "WZL-WM Factory",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Factory Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Factory Name",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "db.b24/factories.aggregate([\n{ \"$match\": { \"physical_resource.abstract_resource.name\" : \"WZL-WM\" }},\n{ \"$sort\": {\"_id\":-1}},\n{ \"$project\": { \"description\": \"$physical_resource.abstract_resource.name\" , \"_id\" : 0}},\n{ \"$limit\": 1 }\n])",
     "type": "table"
    }
   ]
  },
  {
   "title": "Factory Basic Description",
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "db.b24/factories.aggregate([\n{ \"$match\": { \"physical_resource.abstract_resource.name\" : \"WZL-WM\" }},\n{ \"$sort\": {\"_id\":-1}},\n{ \"$project\": { \"description\": \"$physical_resource.abstract_resource.description\" , \"_id\" : 0}},\n{ \"$limit\": 1 }\n])",
     "type": "table"
    }
   ]
  },
  {
   "title": "Factory Capabilities",
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "db.b24/factories.aggregate([\n{ \"$match\": { \"physical_resource.abstract_resource.name\" : \"WZL-WM\" }},\n{ \"$sort\": {\"_id\":-1}},\n{ \"$project\": { \"capabilities\":  {\"$concatArrays\" : \"$physical_resource.abstract_resource.offered_capabilities\"} , \"_id\" : 0}},\n{ \"$limit\": 1 }\n])",
     "type": "table"
    }
   ]
  },
  {
   "title": "Factory State",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "db.b24/factories.aggregate([\n{ \"$match\": { \"physical_resource.abstract_resource.name\" : \"WZL-WM\" }},\n{ \"$sort\": {\"_id\":-1}},\n{ \"$project\": { \"state\" : \"$factory_state.factory_state_string\" , \"_id\" : 0}},\n{ \"$limit\": 1 }\n])",
     "type": "table"
    }
   ]
  },
  {
   "title": "Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "targets": [
    {}
   ]
  },
  {
   "title": "Resource Name",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "db.b24/resources.aggregate([\n{ \"$match\": { \"physical_resource.abstract_resource.name\" : \"KUKA_KRC4\", \"physical_resource.abstract_resource.factory\" : \"WZL-WM\" }},\n{ \"$sort\": {\"_id\":-1}},\n{ \"$project\": { \"name\": \"$physical_resource.abstract_resource.name\" , \"_id\" : 0}},\n{ \"$limit\": 1 }\n])",
     "type": "table"
    }
   ]
  },
  {
   "title": "Resource Type",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "db.b24/resources.aggregate([\n{ \"$match\": { \"physical_resource.abstract_resource.name\" : \"KUKA_KRC4\" , \"physical_resource.abstract_resource.factory\" : \"WZL-WM\"}},\n{ \"$sort\": {\"_id\":-1}},\n{ \"$project\": { \"type\": \"$type.abstract_type.name\" , \"_id\" : 0}},\n{ \"$limit\": 1 }\n])",
     "type": "table"
    }
   ]
  },
  {
   "title": "Resource State",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "db.b24/resources.aggregate([\n{ \"$match\": { \"physical_resource.abstract_resource.name\" : \"KUKA_KRC4\", \"physical_resource.abstract_resource.factory\" : \"WZL-WM\" }},\n{ \"$sort\": {\"_id\":-1}},\n{ \"$project\": { \"state\": \"$robot_state.robot_state_string\" , \"_id\" : 0}},\n{ \"$limit\": 1 }\n])",
     "type": "table"
    }
   ]
  },
  {
   "title": "Resource Description",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "db.b24/resources.aggregate([\n{ \"$match\": { \"physical_resource.abstract_resource.name\" : \"KUKA_KRC4\", \"physical_resource.abstract_resource.factory\" : \"WZL-WM\" }},\n{ \"$sort\": {\"_id\":-1}},\n{ \"$project\": { \"description\": \"$physical_resource.abstract_resource.description\" , \"_id\" : 0}},\n{ \"$limit\": 1 }\n])",
     "type": "table"
    }
   ]
  },
  {
   "title": "KUKA KRC4 Position",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "m " } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "db.b24/resources.aggregate([\n{ \"$match\": { \"physical_resource.abstract_resource.name\" : \"KUKA_KRC4\", \"physical_resource.abstract_resource.factory\" : \"WZL-WM\" }},\n{ \"$sort\": {\"_id\":-1}},\n{ \"$project\": { \"X: \": \"$current_pose.position.x\" , \"Y: \": \"$current_pose.position.y\" , \"Z: \": \"$current_pose.position.z\", \"_id\" : 0}},\n{ \"$limit\": 1 }\n])",
     "type": "table"
    }
   ]
  },
  {
   "title": "KUKA KRC4 Orientation",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "db.b24/resources.aggregate([\n{ \"$match\": { \"physical_resource.abstract_resource.name\" : \"KUKA_KRC4\", \"physical_resource.abstract_resource.factory\" : \"WZL-WM\" }},\n{ \"$sort\": {\"_id\":-1}},\n{ \"$project\": { \"x: \": \"$current_pose.orientation.x\" , \"y: \": \"$current_pose.orientation.y\" , \"z: \": \"$current_pose.orientation.z\", \"w: \": \"$current_pose.orientation.z\", \"_id\" : 0}},\n{ \"$limit\": 1 }\n])",
     "type": "table"
    }
   ]
  }
 ]
}